### ISSUE TITLE
Dispose takes a long time to return

### ISSUE THREAD

**Issue by fadif91** [mlockett42/litedb-async#14]
Hi,

When using the LiteDatabaseAsync object in a using block, doing work then returning, it should run the dispose method. I noticed this takes a long time to complete. Anything going on in dispose ?

Thank you

**Comment by fadif91** [comment]
Ok by looking at the source code you are waiting 5 sec. This means that the recommended using block pattern shouldn't be used and only use one instance of LiteDatabseAsync

**Comment by mlockett42** [comment]
Yes I recommend only one global instance of LiteDatabaseAsync
