### ISSUE TITLE
Change GetCollection return type to interface

### ISSUE THREAD

**Issue by jspinner13** [mlockett42/litedb-async#16]
The current LiteDatabaseAsync.GetCollection method is not so easy to test.
I would expect ILiteCollectionAsync instead of LiteCollectionAsync because the interface is mockable.

**Comment by mlockett42** [comment]
Does this PR do what you want?
https://github.com/mlockett42/litedb-async/pull/17

**Comment by MKuckert** [comment]
Are you planning to release a new nuget package containing this change?

**Comment by mlockett42** [comment]
Yes in the next few days

**Comment by mlockett42** [comment]
v0.0.10 containing this update just been pushed to nuget
