### ISSUE TITLE
Methods are completed on background thread if ConfigureAwait(false) is used

### ISSUE THREAD

**Issue by MKuckert** [mlockett42/litedb-async#18]
We've observed that the background thread may leak to the consuming application. This is especially true in dotnet console applications – like an ordinary unittest project. UI-based platforms like WPF or Xamarin may behave differently but I haven't tested that (yet).

You can find a failing test [in this commit](https://github.com/slashwhy/litedb-async/commit/afe17232e8c0dea98bdbb6743629359b75c1b60e).

### The underlying flow is this:

- application performs an async operation, like an `InsertAsync`, and awaits the result, using `ConfigureAwait(false)` (1)
- litedb-async enqueues a lambda to perform an operation on the background thread
    - this includes a task completion source to return the result to the caller
- the background thread performs the lambda
- the lambda completes the task completion source (2)
- the consuming application returns from its await (1) – without switching back to its initial synchronization context, as dictated by `ConfigureAwait(false)`
- the consuming application disposes the litedb-async
    - the dispose method attempts to cancel the background thread
    - waiting for the background threads completion (by calling `_backgroundThread.Join`) runs into the provided timeout of 5 seconds. One can observe this with a breakpoint on the `tooslow`-variable introduced in [this commit](https://github.com/slashwhy/litedb-async/commit/afe17232e8c0dea98bdbb6743629359b75c1b60e).
    - As a result the background thread has not finished yet
- the consuming application moves on, maybe leaves the method and though the blocking async operation on the background thread
- the lambda (2) completes
- the background threads loop breaks and the thread completes

This essentially is a deadlock on the `backgroundThread.Join` being called from the background thread itself, which is only cancelled by the timeout.

Not using `ConfigureAwait(false)` does indeed fix the issue – but it's pretty common practice to use this configuration, at least in library projects.

### So, what could one do?

1. The consuming application could try to ensure to always dispose from another thread
2. The consuming application could stop using `ConfigureAwait(false)`
3. The completion of the task completion source could run on another thread, e.g. on the thread pool

Solution 1 would require proper handling in the application – thats not too complication but one has to know that. One can add a sentence to the documentation, but, meeh

Solution 2 would kind of go against common practice. It's probably not that easy to refrain from typical development patterns here, so, meeh.

Solution 3 would require a change on the libraries implementation for every operation completing its task completion source to run all waiting operations on a separate thread. Good luck this is a supported framework feature: One can simply pass `TaskCreationOptions.RunContinuationsAsynchronously` to the task completion sources constructor.

I would totally prefer solution 3 as it's the one with the least headaches and doesn't require special treatment from the application developer. But it's kind of a breaking change.
What do you thing? I'm willing to provide a pull request changing all the `TaskCompletionSource<>` calls appropriately.

**Comment by MKuckert** [comment]
I've created a pull request to simply pass `TaskCreationOptions.RunContinuationsAsynchronously` to all task completion sources. This works for all unit tests but am unsure if that's a proper solution.

**Comment by MKuckert** [comment]
@mlockett42 Any thoughts on this?

**Comment by mlockett42** [comment]
Going to test this out today including on the mvvm cross / xamarin forms test project

**Comment by mlockett42** [comment]
This is now uploaded as v0.0.11

@MKuckert Also can I ask you how you heard about LiteDb.Async?

**Comment by MKuckert** [comment]
@mlockett42 We've been using LiteDB for multiple apps and lately decided that we'd like to separate the database operations from the main thread. A college of mine nearly started implementing our own wrapper but then found this library - so google told us.
