### ISSUE TITLE
Expressions

### ISSUE THREAD

**Issue by Avatarchik** [mlockett42/litedb-async#2]
How can i use? https://github.com/mbdavid/LiteDB/wiki/Expressions

**Comment by mlockett42** [comment]
I will need to add the feature, I will see if there is an easy way to do that.

**Comment by Avatarchik** [comment]
Hi! Is there any news?

**Comment by mlockett42** [comment]
I have added a unit test to demostrate this

https://github.com/mlockett42/litedb-async/blob/1e3abf790d220a3b031360efb2aa9c5c90fca6ae/litedbasynctest/Query/Where_Tests.cs#L32

One thing that confused me at first is you need to import the BsonExpression class from LiteDb, there didn't seem to be a practical way I could repackage it in LiteDb.Async

Also may be help to update to 0.0.3 https://www.nuget.org/packages/LiteDB.Async/0.0.3
It works correctly with litedb 5.0.9 and fixes another bug.
