### ISSUE TITLE
Example of how to use UpsertManyAsync ?

### ISSUE THREAD

**Issue by stephenhauck** [mlockett42/litedb-async#20]
Can you offer an example of how to implement UpsertManyAsync in code ?

**Comment by mlockett42** [comment]
There is no UpsertMany in the underlying LiteDb but Upsert (and therefore UpsertAsync) can accept a IEnumerable, which I assume is the equivalent functionality

I have added a unit test to demonstrate this functionality https://github.com/mlockett42/litedb-async/blob/cfefdf4b9fdd92470badbf273c83cd967e52d3d9/litedbasynctest/Database/Upsert_Many_Tests.cs
