### ISSUE TITLE
Running under load, LiteRepositoryAsync  keeping file lock after Disposing

### ISSUE THREAD

**Issue by Pete-PlaytimeSolutions** [mlockett42/litedb-async#26]
When running under load , after disposing of the ILiteRepositoryAsync, the UnderlyingDatabase is still holding onto a File lock. I think, due to not immediately disposing of the UnderlyingDatabase too.

This was my simple fix, around line 337 of LiteRepositoryAsync.cs

```
protected virtual void Dispose(bool disposing)
{
       if (disposing)
       {
            // BUGFIX: Ensure UnderlyingDatabase is immediately disposed of..._
            _db.UnderlyingDatabase.Dispose();
            _db.Dispose();
       }
}
```

**Comment by mlockett42** [comment]
This fix has been added and uploaded as v0.1.5
