### ISSUE TITLE
typo: namespace of `ILiteRepositoryAsync` should be `LiteDB.Async` (?)

### ISSUE THREAD

**Issue by zmira** [mlockett42/litedb-async#33]
The namespace of `ILiteRepositoryAsync` is currently defined as `LiteDB.async` (lower-case `a`) @ https://github.com/mlockett42/litedb-async/blob/incoming/LiteDBAsync/ILiteRepositoryAsync.cs#L7.

Should it not be `LiteDB.Async` (upper-case `A`)?

**Comment by mlockett42** [comment]
Fixed in Version v0.1.18
