### ISSUE TITLE
 Usage with LiteDb 5.0.9 is broken

### ISSUE THREAD

**Issue by xucito** [mlockett42/litedb-async#4]
When you use this package with litedb 5.0.9 (latest stable), functions are not found.

![image](https://user-images.githubusercontent.com/36687889/94075768-d4b64880-fe0c-11ea-9a46-3b762a68cb89.png)

**Comment by mlockett42** [comment]
I have added a unit test from this scenario - it seems to pass with the latest version

https://github.com/mlockett42/litedb-async/commit/9d05b4ab1e8dfad0a6336516a9c377953fc1d704#diff-43db10209017ad5cea9b7a879dbaf71b

**Comment by mlockett42** [comment]
Please upgrade to version 0.0.3 in nuget it should start working with version 5.0.9

https://www.nuget.org/packages/LiteDB.Async/0.0.3

It looks like the upstream LiteDb developer changed the signature one of the methods causing this error. Let me know if it still gives you problems
